qsub testgrid.sh gdb 1
qsub testgrid.sh gdb 2
qsub testgrid.sh gdb 3
qsub testgrid.sh gdb 4
qsub testgrid.sh gdb 5
qsub testgrid.sh gdb 6
qsub testgrid.sh gdb 7
qsub testgrid.sh gdb 8
qsub testgrid.sh gdb 9
qsub testgrid.sh gdb 10
qsub testgrid.sh gdb 11
qsub testgrid.sh gdb 12
qsub testgrid.sh gdb 13
qsub testgrid.sh gdb 14
qsub testgrid.sh gdb 15
qsub testgrid.sh gdb 16
qsub testgrid.sh gdb 17
qsub testgrid.sh gdb 18
qsub testgrid.sh gdb 19
qsub testgrid.sh gdb 20
qsub testgrid.sh gdb 21
qsub testgrid.sh gdb 22
qsub testgrid.sh gdb 23

qsub testgrid.sh val 1A
qsub testgrid.sh val 1B
qsub testgrid.sh val 1C
qsub testgrid.sh val 2A
qsub testgrid.sh val 2B
qsub testgrid.sh val 2C
qsub testgrid.sh val 3A
qsub testgrid.sh val 3B
qsub testgrid.sh val 3C
qsub testgrid.sh val 4A
qsub testgrid.sh val 4B
qsub testgrid.sh val 4C
qsub testgrid.sh val 4D
qsub testgrid.sh val 5A
qsub testgrid.sh val 5B
qsub testgrid.sh val 5C
qsub testgrid.sh val 5D
qsub testgrid.sh val 6A
qsub testgrid.sh val 6B
qsub testgrid.sh val 6C
qsub testgrid.sh val 7A
qsub testgrid.sh val 7B
qsub testgrid.sh val 7C
qsub testgrid.sh val 8A
qsub testgrid.sh val 8B
qsub testgrid.sh val 8C
qsub testgrid.sh val 9A
qsub testgrid.sh val 9B
qsub testgrid.sh val 9C
qsub testgrid.sh val 9D
qsub testgrid.sh val 10A
qsub testgrid.sh val 10B
qsub testgrid.sh val 10C
qsub testgrid.sh val 10D

