qsub testgrid.sh egl -e1-A
qsub testgrid.sh egl -e1-B
qsub testgrid.sh egl -e1-C
qsub testgrid.sh egl -e2-A
qsub testgrid.sh egl -e2-B
qsub testgrid.sh egl -e2-C
qsub testgrid.sh egl -e3-A
qsub testgrid.sh egl -e3-B
qsub testgrid.sh egl -e3-C
qsub testgrid.sh egl -e4-A
qsub testgrid.sh egl -e4-B
qsub testgrid.sh egl -e4-C
qsub testgrid.sh egl -s1-A
qsub testgrid.sh egl -s1-B
qsub testgrid.sh egl -s1-C
qsub testgrid.sh egl -s2-A
qsub testgrid.sh egl -s2-B
qsub testgrid.sh egl -s2-C
qsub testgrid.sh egl -s3-A
qsub testgrid.sh egl -s3-B
qsub testgrid.sh egl -s3-C
qsub testgrid.sh egl -s4-A
qsub testgrid.sh egl -s4-B
qsub testgrid.sh egl -s4-C
